### ISSUE TITLE
Ibarra Real render on Browsers

### ISSUE THREAD

**Issue by vv-monsalve** [vv-monsalve/ibarrareal#1]
### OS X High Sierra Safari 11
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/67578510-32777780-f708-11e9-9afd-75c707d6faaf.jpg)

### Windows 10 Chrome 69
![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/67578511-32777780-f708-11e9-946d-21bf43a612fd.jpg)

### Windows 10 Firefox 62
![Desktop_Windows_10_firefox_62 0_](https://user-images.githubusercontent.com/48698976/67578512-32777780-f708-11e9-9825-e3884973e3be.jpg)

**Comment by vv-monsalve** [comment]
### Windows 10 Chrome 69
![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/67578886-ff81b380-f708-11e9-95ed-f533856dc64c.jpg)

**Comment by m4rc1e** [comment]
Release the font unhinted.

**Comment by arrowtype** [comment]
(One thing I'm seeing here: it looks like the vertical metrics might be mismatching between macOS and Windows. Probably, this either needs matching vertical metrics, or possibly it needs the MVAR table removed.)

**Comment by m4rc1e** [comment]
@arrowtype agreed. @vv-monsalve make sure the hhea and os/2 typo metrics are the same,

**Comment by vv-monsalve** [comment]
Thanks. This is project has 0 Fail on vertical metrics. It has Use Typo Metris enabled (not sure if this affects this rendering in any way apart from leading). 
Picture of current values for masters:
![Screen Shot 2019-10-25 at 11 29 47](https://user-images.githubusercontent.com/48698976/67588135-f6014700-f71a-11e9-8940-3906dbd0db03.png)
![Screen Shot 2019-10-25 at 11 29 55](https://user-images.githubusercontent.com/48698976/67588136-f6014700-f71a-11e9-939f-d6885d6f1df9.png)

**Comment by vv-monsalve** [comment]
Vertical metrics and stems reviewed. I think the hinted version works better than unhinted

### Windows 10 Chrome 69 / Hinting
![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/68009707-a78b0580-fc50-11e9-843a-aaaf7dcbb050.jpg)

### Windows 10 Chrome 69 / No Hinting
![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/68009758-c9848800-fc50-11e9-915f-4bb6ec444921.jpg)

Vertical Metrics
<img width="813" alt="Screen Shot 2019-11-01 at 02 35 04" src="https://user-images.githubusercontent.com/48698976/68009789-e325cf80-fc50-11e9-9b18-d7207cc09270.png">
<img width="813" alt="Screen Shot 2019-11-01 at 02 35 13" src="https://user-images.githubusercontent.com/48698976/68009790-e3be6600-fc50-11e9-8123-6719547c1f26.png">

**Comment by vv-monsalve** [comment]
Solved this after hangout with Marc. Thanks!
